/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.CheckService;
import service.PrintService;
import static util.Util.*;

/**
 *
 * @author vinicius
 */
public class JFrameListCheck extends javax.swing.JFrame {

    /**
     * Creates new form JFrameList
     */
    public JFrameListCheck() {
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableChecks = new javax.swing.JTable();
        jButtonPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButtonRefresh.setText("Consultar");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        jTableChecks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "N° Matricula", "N° RG", "N° Cheque", "Valor", "Valor por Extenso", "Nome do Associado", "Data", "Limite por Folha", "Validade", "Impressões"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableChecks);
        if (jTableChecks.getColumnModel().getColumnCount() > 0) {
            jTableChecks.getColumnModel().getColumn(0).setMinWidth(50);
            jTableChecks.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableChecks.getColumnModel().getColumn(0).setMaxWidth(50);
            jTableChecks.getColumnModel().getColumn(1).setMinWidth(80);
            jTableChecks.getColumnModel().getColumn(1).setPreferredWidth(80);
            jTableChecks.getColumnModel().getColumn(1).setMaxWidth(80);
            jTableChecks.getColumnModel().getColumn(2).setMinWidth(80);
            jTableChecks.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTableChecks.getColumnModel().getColumn(2).setMaxWidth(80);
            jTableChecks.getColumnModel().getColumn(3).setMinWidth(80);
            jTableChecks.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTableChecks.getColumnModel().getColumn(3).setMaxWidth(80);
            jTableChecks.getColumnModel().getColumn(4).setMinWidth(100);
            jTableChecks.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTableChecks.getColumnModel().getColumn(4).setMaxWidth(100);
            jTableChecks.getColumnModel().getColumn(7).setMinWidth(80);
            jTableChecks.getColumnModel().getColumn(7).setPreferredWidth(80);
            jTableChecks.getColumnModel().getColumn(7).setMaxWidth(80);
            jTableChecks.getColumnModel().getColumn(8).setMinWidth(100);
            jTableChecks.getColumnModel().getColumn(8).setPreferredWidth(100);
            jTableChecks.getColumnModel().getColumn(8).setMaxWidth(100);
            jTableChecks.getColumnModel().getColumn(9).setMinWidth(80);
            jTableChecks.getColumnModel().getColumn(9).setPreferredWidth(80);
            jTableChecks.getColumnModel().getColumn(9).setMaxWidth(80);
            jTableChecks.getColumnModel().getColumn(10).setMinWidth(80);
            jTableChecks.getColumnModel().getColumn(10).setPreferredWidth(80);
            jTableChecks.getColumnModel().getColumn(10).setMaxWidth(80);
        }

        jButtonPrint.setText("Imprimir");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1124, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPrint, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonRefresh, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPrint)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        try {
            DefaultTableModel model = (DefaultTableModel) jTableChecks.getModel();
            model.setRowCount(0);
            for (Object check : (new CheckService()).getChecks()) {
                model.addRow((Object[]) check);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, getErrorMessage(e), "Opa", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        try {
            if (jTableChecks.getSelectedRowCount() == 0) {
                JOptionPane.showMessageDialog(
                        rootPane,
                        "Selecione um cheque para imprimir!",
                        "Opa!",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            for (int selectedRow : jTableChecks.getSelectedRows()) {
                int id = Integer.parseInt(jTableChecks.getValueAt(selectedRow, 0).toString());
                JOptionPane.showMessageDialog(
                        rootPane,
                        (new PrintService()).print("cheque", id),
                        "Impressão",
                        JOptionPane.INFORMATION_MESSAGE
                );
            }
            jButtonRefreshActionPerformed(evt);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, getErrorMessage(e), "Opa", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameListCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameListCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameListCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameListCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameListCheck().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableChecks;
    // End of variables declaration//GEN-END:variables
}
